// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbukhgwpazmtlyyqgnjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidWtoZ3dwYXptdGx5eXFnbmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjc3NzMsImV4cCI6MjA3MTgwMzc3M30.GtB7fXBE5fLtJQm5C0qHn2kyyH5KYsbUoixG6V8ujOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});